### ISSUE TITLE
Doesn't Run

### ISSUE THREAD

**Issue by randyaa** [mgechev/ngworld#2] opened 2017-06-07 13:19 UTC
I know this is just a demo project for you and not that critical but i saw it and thought it would be a fun little thing to try for our fairly large app. Installed globally and ran resulting in a bunch of errors like so:
```
ngworld -p .
�  Creating a program...
✅  Program created!
Error: Could not resolve module @angular/core
```
(with stack traces)

also got errors like these:
```
Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
    at simplify (userprofile\npm\node_modules\ngworld\node_modules\@angular\compiler\bundles\compiler.umd.js:23849:54)
```

Just letting you know. Not critical for me in any way.

Thanks!

**Comment by mgechev** [comment] 2017-06-07 13:24
Thanks for letting me know. The issue can be caused by a few reasons:

- You haven't installed the dependencies of the project that ngworld parses.
- The versions of Angular are different.

Since, as you mentioned, this is a demo project and I'm not planning to maintain it further I'll close the issue.

**Closed by mgechev** 2017-06-07 13:24 UTC
